AudioConsts = 
{
  ACT4FUN_LIVELOADING = "ON_ACT4FUN_LIVELOADING";
  ACT4FUN_PHOTOUNFLOAD = "ON_ACT4FUN_PHOTOUNFLOD";
  ACT4FUN_PHOTOFIX = "ON_ACT4FUN_PHOTOFIX";
  ACT4FUN_SCHINT = "ON_ACT4FUN_SCHINT";
  ACT4FUN_SCINTERACT = "ON_ACT4FUN_SCINTERACT";
  ACT4FUN_VALUE_TOAST = "ON_ACT4FUN_SCINCREASE";
  ACT4FUN_VALUE_BOOM_UP = "ON_ACT4FUN_SCFULL";
  ACT4FUN_VALUE_BOOM_LOW = "ON_ACT4FUN_SCLACK";
  ACT4FUN_END_FAILED = "ON_ACT4FUN_SCWARNING";
  ACT1SIGNVS_BOAT_ENTER = "ON_ACT1SIGNVS_DRAGONBOATLOAD";
  ACT1SIGNVS_BOAT_URGE = "ON_ACT1SIGNVS_DRAGONBOATURGE";
  ACT1BLESSING_PACKET_ENTRY = "ON_ACT1BLESSING_SFSGNENTR";
  ACT1BLESSING_OPEN_PACKET = "ON_ACT1BLESSING_SFSGNOPN";
  ACT5FUN_ENTER = "ON_ACT5FUN_ENTER";
  ACT5FUN_ENTERPRO = "ON_ACT5FUN_ENTERPRO";
  ACT5FUN_MONEYEXPLODE = "ON_ACT5FUN_MONEYEXPLODE";
  ACT5FUN_FUNDSETTLEMENT = "ON_ACT5FUN_FUNDSETTLEMENT";
  ACT5FUN_SHATTERRECORD = "ON_ACT5FUN_SHATTERRECORD";
}
AudioConsts = Readonly(AudioConsts);