require "Feature/Main/MainDlg"
require "Feature/Main/TestDlg"

require "Feature/Activity/Collection/CollectionItem"
require "Feature/Activity/Collection/CollectionMainDlg"
require "Feature/Activity/Collection/CollectionTaskListDlg"
require "Feature/Activity/Collection/CollectionActModel"
require "Feature/Activity/Collection/CollectionDailyTaskItem"
require "Feature/Activity/Collection/CollectionTimedTaskItem"
require "Feature/Activity/LoginOnly/LoginOnlyDefine"
require "Feature/Activity/LoginOnly/LoginOnlyDlg"

require "Feature/Activity/Act3D5/Act3D5Dlg"
require "Feature/Activity/Act4D5/Act4D5Dlg"
require "Feature/Activity/Act6D8/Act6D8Dlg"
require "Feature/Activity/Act9D1D2/Act9D1D2Dlg"
require "Feature/Activity/Act9D4/Act9D4Dlg"